{% set name = "nestd" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/nestd-{{ version }}.tar.gz
  sha256: 1b946d2bbc16df67ca169b8cb59794ec70b54d4a56a017e3d1c092d364d22a39

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7,<4.0
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.7,<4.0

test:
  imports:
    - nestd
  commands:
    - pip check
  requires:
    - pip

about:
  home: None
  summary: A package to extract your nested functions!
  license: BSD-2-Clause
  license_file: LICENCE.md

extra:
  recipe-maintainers:
    - thewchan
