{% set name = "nestd" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/nestd-{{ version }}.tar.gz
  sha256: 111e59a7d86bebe903d736a1c7a652c1e75a1c31d5b8aae3b416b7cb2e5ba8e5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - pip
  run:
    - python >={{ python_min }},<4.0

test:
  imports:
    - nestd
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: None
  summary: A package to extract your nested functions!
  license: BSD-2-Clause
  license_file: LICENCE.md

extra:
  recipe-maintainers:
    - thewchan
